autodetect: yes
doc-warnings: yes
max-line-length: 80
uses:
  - django
pylint:
  run: true
pep8:
  full: true
python-targets:
  - 3
requirements:
  - requirements.txt
ignore-patterns:
  - (^|/)migrations(/|$)
strictness: veryhigh
test-warnings: yes
