language: python
python:
  - 3.4
  - 3.5
install:
  - pip install -r requirements.txt
script:
  - coverage run --source="." --omit="*migrations*" caffe/manage.py test caffe
notifications:
  slack: io-kawiarnie:9weIop9A462y5IzoQEBI90Ps
