version: '2'
services:
  db:
    restart: always
    image: sameersbn/postgresql:9.4-18
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=db
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql
  web:
    build: .
    command: ./start-web.sh
    volumes:
      - .:/app
    ports:
      - "80:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=settings.production
