version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: ./start-web.sh
    volumes:
      - .:/app
    ports:
      - "80:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=settings.production
