version: '2'
services:
  web:
    restart: always
    build: .
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - .:/app
    command: ./start-web.sh
    environment:
      - DJANGO_SETTINGS_MODULE=settings.production

  postgres:
    restart: always
    image: postgres:latest
    volumes_from:
      - data
    ports:
      - "5432:5432"

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"

  data:
    restart: always
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"
