# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 17:49
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='date',
            new_name='created_on',
        ),
        migrations.AlterField(
            model_name='fullproduct',
            name='report',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Report'),
        ),
    ]
