# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 20:58
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20160414_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullproduct',
            name='report',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='full_products', to='reports.Report'),
        ),
    ]
