# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 08:22
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20160414_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 19, 8, 22, 19, 595337, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
