# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-11 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caffe', '0001_initial'),
        ('reports', '0007_auto_20160521_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='caffe',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='caffe.Caffe'),
        ),
        migrations.AddField(
            model_name='fullproduct',
            name='caffe',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='caffe.Caffe'),
        ),
        migrations.AddField(
            model_name='product',
            name='caffe',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='caffe.Caffe'),
        ),
        migrations.AddField(
            model_name='report',
            name='caffe',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='caffe.Caffe'),
        ),
        migrations.AddField(
            model_name='unit',
            name='caffe',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='caffe.Caffe'),
        ),
    ]
