# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-19 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20160611_1614'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('name', 'caffe')]),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('name', 'caffe')]),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set([('name', 'caffe')]),
        ),
    ]
