# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 17:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workedhours',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ('-date', '-end_time')},
        ),
        migrations.AddField(
            model_name='workedhours',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 31, 19, 42, 6, 926804)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workedhours',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 31, 19, 42, 12, 376188)),
            preserve_default=False,
        ),
    ]
