# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 20:40
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workedhours',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ('-date', '-end_time')},
        ),
        migrations.AddField(
            model_name='workedhours',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 31, 20, 40, 21, 720775, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workedhours',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 31, 20, 40, 25, 110438, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workedhours',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
