# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 11:54
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caffe', '0001_initial'),
        ('hours', '0003_auto_20160601_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='caffe',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='caffe.Caffe'),
        ),
        migrations.AddField(
            model_name='workedhours',
            name='caffe',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='caffe.Caffe'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
