# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-10 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caffe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('house_number', models.CharField(max_length=10)),
                ('building_number', models.CharField(blank=True, max_length=10)),
                ('created_on', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
