# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-18 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caffe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caffe',
            name='building_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='caffe',
            name='house_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
