# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ksywka',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
