# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_ksywka'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='ksywka',
            new_name='ulubiona_kawa',
        ),
    ]
