# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20160513_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='ulubiona_kawa',
            new_name='favorite_coffee',
        ),
    ]
