# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20160521_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ('last_name', 'first_name')},
        ),
    ]
