# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-10 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caffe', '__first__'),
        ('employees', '0006_auto_20160521_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='caffe',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='caffe.Caffe'),
        ),
    ]
