# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-20 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_caffe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='favorite_coffee',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
