# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0004_auto_20160521_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashreport',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ('-created_on', '-updated_on')},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ('name', 'company')},
        ),
        migrations.RenameField(
            model_name='cashreport',
            old_name='author',
            new_name='creator',
        ),
    ]
