# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0005_auto_20160521_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fullexpense',
            old_name='destination',
            new_name='expense',
        ),
    ]
