# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0008_auto_20160615_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fullexpense',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
        migrations.AlterField(
            model_name='fullexpense',
            name='cash_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='full_expenses', to='cash.CashReport'),
        ),
    ]
