# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-19 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0010_auto_20160619_1702'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together=set([]),
        ),
    ]
