# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0004_auto_20160414_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stencil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('categories', models.ManyToManyField(to='reports.Category')),
            ],
        ),
    ]
