# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stencils', '0002_stencil_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stencil',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ('name', 'description')},
        ),
    ]
