# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 05:57
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caffe', '0001_initial'),
        ('stencils', '0003_auto_20160521_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='stencil',
            name='caffe',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='caffe.Caffe'),
        ),
    ]
